### ISSUE TITLE
mlton requirement

### ISSUE THREAD

**Issue by xrchz** [acjf3/l3mips#6]
Although the `readme` suggests `polyml` is all that is required, if I try to run `make` it fails with `/bin/sh: mlton: command not found`. Is this a mistake in the dependencies, or in some configuration?

**Comment by gameboo** [comment]
woops... The readme is probably slightly stale... I am going to fix this, but basically, if you `make poly`, mlton should not be required.
Edit:
Does [this](https://github.com/acjf3/l3mips/commit/2620a447a847505bb1ddbf172b0df89ad3625295) do the trick?

**Comment by xrchz** [comment]
yep, I believe so!
