### ISSUE TITLE
src/l3/mips-cache-sizes.spec

### ISSUE THREAD

**Issue by xrchz** [acjf3/l3mips#7]
Should this file be either in the repository or ignored? It seems like a generated build product...

**Comment by gameboo** [comment]
I believe this file is indeed generated and is not versioned... The one that is versioned is mips-cache-sizes.spec.m4. Did you get this file after a git clone?

**Comment by gameboo** [comment]
BTW, if the generated file is biting you between builds, it should be taken care of by a `make clean`. I guess the clean way to deal with this would be to have separate build directories, but we removed almost all of the features that were backed by generated files, and the caches are not really ever used.

**Comment by xrchz** [comment]
I suggest adding the generated file to the `.gitignore`

**Comment by gameboo** [comment]
sure thing!
[committed](https://github.com/acjf3/l3mips/commit/7160d1ea9cc9ddd80cef5af8fc3acd9d1c75b364)
thanks
